# host address for ingress resource
host: auto-oncall.6iec4.k8s.gollum.westeurope.azure.gigantic.io
# Github organization webhook secret
githubWebhookSecret: secret
# deployment namespace
namespace: operations
tls:
  enabled: true
  issuerType: ClusterIssuer
  issuerName: letsencrypt-prod
# list of applications, configured for automated oncall rules
repositories:
  - test-oncall
# Opsgenie token string
opsgenieToken: 6817602c-0174-4a08-a8df-ee7f24981296
# user mapping `github_user:opsgenie user' 
users:
  "corest": "vol@giantswarm.io"
