apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      oncall:
        {{- $oncall := dict "users" (list) }}
        {{- range $key, $val := .Values.users -}}
        {{- $noop := printf "%s:%s" $key $val | append $oncall.users | set $oncall "users" -}}
        {{- end }}
        users: {{ join "," $oncall.users }} 
