apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
      - name: {{ .Values.name }}-configmap
        configMap:
          name: {{ .Values.name }}-configmap
          items:
          - key: config.yaml
            path: config.yaml
      - name: {{ .Values.name }}-secret
        secret:
          secretName: {{ .Values.name }}-secret
          items:
          - key: secret.yaml
            path: secret.yaml
      containers:
      - name: {{ .Values.name }}
        image: quay.io/giantswarm/{{ .Values.name }}:latest
        volumeMounts:
        - name: {{ .Values.name }}-configmap
          mountPath: /var/run/{{ .Values.name }}/configmap/
        - name: {{ .Values.name }}-secret
          mountPath: /var/run/{{ .Values.name }}/secret/
          readOnly: true
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/{{ .Values.name }}/configmap/
        - --config.dirs=/var/run/{{ .Values.name }}/secret/
        - --config.files=config
        - --config.files=secret
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 25m
            memory: 25Mi
