apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.AutoOncall.SecretYaml | b64enc | quote }}
