{{- if .Values.tls.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: auto-oncall
  namespace: {{ .Values.namespace }}
spec:
  secretName: auto-oncall-certs
  dnsNames:
  - {{ .Values.host }}
  acme:
    config:
    - domains:
      - {{ .Values.host }}
      http01:
        ingress: ""
  issuerRef:
    kind: {{ .Values.tls.issuerType }}
    name: {{ .Values.tls.issuerName }}
{{- end }}
