apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-oncall-configmap
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    repositories: 
    {{- range .Values.repositories }}
    - {{ . }}
    {{- end }}
    users:
      {{- range $key, $val := .Values.users }}
      {{ $key }}: {{ $val | quote }}
      {{- end}}
