apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: auto-oncall-secret
  namespace: {{ .Values.namespace }}
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.AutoOncall.SecretYaml | b64enc | quote }}
